version: "3"
services:
    alist:
        restart: always
        volumes:
            - /media/U盘:/media/U盘
            - /root/alist:/opt/alist/data
        ports:
            - 5244:5244
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: xhofe/alist:latest